# Generated by Django 2.1.5 on 2019-01-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('TRADE_SUCCESS', '成功'), ('TRADE_CLOSE', '交易关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
