# Generated by Django 2.1.4 on 2019-01-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cont', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gbook',
            },
        ),
    ]
