# Generated by Django 2.1.5 on 2019-01-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_browse'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='browse',
            table='browse',
        ),
    ]
