# Generated by Django 2.1.5 on 2019-01-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190117_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browse',
            old_name='browse',
            new_name='br',
        ),
    ]
