# Generated by Django 2.1.5 on 2019-01-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190117_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='browse',
            table='f_browse',
        ),
    ]
