# Generated by Django 2.1.4 on 2019-01-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtic', '0002_auto_20190111_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='biaoqian',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='miaoshu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lanmu',
            name='keyword',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lanmu',
            name='mshu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lanmu',
            name='other_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
