# Generated by Django 2.1.4 on 2019-01-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtic', '0003_auto_20190113_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='biaoqian',
            new_name='biaoqian1',
        ),
    ]
