# Generated by Django 2.1.4 on 2019-01-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('crate_time', models.DateField(auto_now_add=True)),
                ('data', models.CharField(max_length=4000)),
                ('icon', models.ImageField(null=True, upload_to='upload')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='LanMu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lanmu',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='lm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airtic.LanMu'),
        ),
    ]
